// flow-typed signature: 292530963c01d372e04736ca6ff355cc
// flow-typed version: <<STUB>>/clipboard_v^2.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipboard/dist/clipboard' {
  declare module.exports: any;
}

declare module 'clipboard/dist/clipboard.min' {
  declare module.exports: any;
}

declare module 'clipboard/package' {
  declare module.exports: any;
}

declare module 'clipboard/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipboard/dist/clipboard.js' {
  declare module.exports: $Exports<'clipboard/dist/clipboard'>;
}
declare module 'clipboard/dist/clipboard.min.js' {
  declare module.exports: $Exports<'clipboard/dist/clipboard.min'>;
}
declare module 'clipboard/package.js' {
  declare module.exports: $Exports<'clipboard/package'>;
}
declare module 'clipboard/webpack.config.js' {
  declare module.exports: $Exports<'clipboard/webpack.config'>;
}
