// flow-typed signature: a9aee1e355717c5a40640f83b62f459a
// flow-typed version: <<STUB>>/react-swipeable-views_v^0.13.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipeable-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipeable-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipeable-views/lib/index' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/SwipeableViews' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/index' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/SwipeableViews' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipeable-views/lib/index.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/index'>;
}
declare module 'react-swipeable-views/lib/SwipeableViews.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/SwipeableViews'>;
}
declare module 'react-swipeable-views/src/index.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/index'>;
}
declare module 'react-swipeable-views/src/SwipeableViews.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/SwipeableViews'>;
}
